services:
  - type: web
    name: administrative-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      npm run migrate && npm run seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: admin-app-db-administrative-app.d.aivencloud.com
      - key: DB_PORT
        value: '18795'
      - key: DB_NAME
        value: defaultdb
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_CA
        value: /etc/secrets/ca.pem
